apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "istio-tracing-java-a.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio-tracing-java-a.name" . }}
    helm.sh/chart: {{ include "istio-tracing-java-a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
