apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-tracing-java-a
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - 'istio-tracing-java.eks5115.github.com'
  http:
  - route:
    - destination:
        host: istio-tracing-java-a
        port:
          number: 80
